dracula = [
    "I'm movin' different.",
    "This shit ain't nothin' to me, man, I'm a dog.",
    "I'm bitin' the fart bubbles in the bath, we smokin' Symbiotes",
    "Smokin' that Whoopi Goldberg, south Egyptian.",
    "Furburger deluxe, Mega Millions scratcher, skunk, Bubba kush.",
    "We smokin' dung beetle.",
    "I'm on twelve Vicodin, smokin' on Scooby-Doo dick.",
    "We smokin' sequoia banshee boogers.",
    "We snortin' that good buffalo soldier, tamarind, Jordanian jibbies.",
    "They must have amnesia, they forgot that I'm him.",
    "That Burberry Backwoods pack hittin'.",
    "That pussy smell like a Hellcat V8.",
    "We smokin' shit in a glass pipe, blowin' the Lord's bubbles.",
    "I'm sick in the head, I'm on them Broward County Tic-Tacs.",
    "I'm on them Georgetown Gеronimos.",
    "I'm on them Nashville nibblers.",
    "I lеft my Margielas in the Benz truck.",
    "I'll have to stunt on them next time.",
    "I don't give a fuck if I go blind.",
    "I don't need to see the price tag anyways.",
    "I'm high on twelve Jason Bournes, lookin' to beat the cum out of a thick, fresh oak.",
    "We're smokin' filtered crack, you stupid piece of shit.",
    "I'll fuckin' kill you.",
    "Call that pussy The Matrix because I'm in this bitch and I can't get out.",
    "Last guy who ran off on the pack got choked out by some Givenchy gloves.",
    "The last thing he ever saw was the price tag on them.",
    "Slowly faded into darkness and I let the archangels take him.",
    "I need more sequoia banshee boogers.",
    "Don't be shy, girl, I love me some pastrami mud flaps.",
    "I'm movin' like French Montana—Haaanh?",
    "Welcome to the cream kingdom, bitch, open up.",
    "Blac Chyna, I'd drink her piss out of another man's balls.",
    "My shooter a crackhead, he look like Woody Harrelson.",
    "You ain't seen ten bands in your life, jit.",
    "Reach for my neck, you'll get turned into an example.",
    "Y'all gotta stop playin' with me, man.",
    "I threw diamonds at the strip clubs under the Great Pyramids.",
    "I pushed the camel through the eye of a needle.",
    "This shit ain't nothin' to me, man.",
    "Tied the ops to the back of a Trackhawk and dragged 'em around the block for 24-hours.",
    "Motherfucker looked like a Resident Evil 5 campaign extra after we was done with him.",
    "Ops wanted some initiative, blew up their entire quadrant.",
    "I'm movin' like Oppenheimer.",
    "She dropped that ass on me from an egregarious angle.",
    "They thought I was Steven Wallace.",
    "Top shelf zaza disrupted my circadian rhythm.",
    "I have seen the Magna Carta, I've seen the Eye of Hora.",
    "I was flippin' bricks for Mansa Musa before y'all even became a type-1 civilization.",
    "This shit ain't nothin' to me, you stupid piece of shit.",
    "Step the wrong way and you will perish.",
    "That pussy feel like Biscoff butter.",
    "You think I care about this shit?",
    "Ask me if I care about this shit, 'cause I don't give a shit.",
    "If I had a dollar for every time they said I gave a shit, I'd be broke.",
    "'Cause I don't give a shit.",
    "My bitch look like David Hasselhoff.",
    "I balled so hard they thought I was a fuckin' nutsack.",
    "This shit ain't nothin' to me, man.",
    "I'll kill you, you stupid piece of shit.",
    "We straight gassing, cutting straight to the bricks.",
    "Ha ha.",
    "This shit ain't nothing to me man.",
    "We smoking runts.",
    "Shorty got a BBL, took that shit out because she couldn't run.",
    "I had to do it to them snipe. I went Judge Judy on that pussy snipe.",
    "I'm not loyal to anybody, I'm a demon. I have no loyalty for anyone. Never did, never will. Shorty chose to be with a demon, sounds like her problem to me, ha ha.",
    "This shit ain't nothing to me man, my money longer than James Cameron.",
    "On and off the court straight fundamentals, no funny business. This shit ain't nothing to me man.",
    "Moving like Dracula we get it back in blood.",
    "You see it? I really did this, I'm really him.",
    "Flipped a whole brick into an Empire. Stop playing with me.",
    "I have no sympathy, I live for this shit. This shit ain't nothing to me man.",
    "I'm nice with it, ha ha.",
    "My money long, my pockets deep. No pocket watching in these parts.",
    "We straight gassing, cutting straight to the bricks.",
    "Chanel Optics got me seeing shit.",
    "This shit ain't nothin' to me, man. ",
    "Haters in shambles. They stay pickin' the corn out of my shit. ",
    "This Smith & Wesson got me movin' like an invasive species. ",
    "I got Midas touch, fuck boi! ",
    "Bitch so bad, I made her shit in my chopped cheese. ",
    "I'm at the bank about to withdraw all of it. ",
    "These Valentinos are from Milan, you fucking idiot. ",
    "That Fentanyl gave me Vitruvian Man flexibility, got me in a state of rigor mortis. ",
    "Caught a broke boy trying to come up on my Amazon package, so I skinned his ass alive. ",
    "Ah! We smoking Serg Ibaka spinal fluid-infused quick-release percs. ",
    "She spread it and let me take a deep sniff of that Mahi Mahi. I gave that pussy a raspberry. ",
    "They needed a stealth soldier, so I put my hands on the hibachi hot plate at Benihana and burned my fucking fingerprints off. They will not find me. Konnichiwa, you little jet. ",
    "Snortin' some premium modest yahoo got me fighting for my life. ",
    "I make a nice stew out of that pussy. ",
    "Blacked out on the Percocet, ordered a Desert Eagle off Amazon. ",
    "I used to nut in my socks until the crust smelled sweet. I ain't never goin' back. ",
    "Hidden Valley Ranch ice cream cake in my fronto leaf got Subanese crystalline shards pokin' out my lungs, fuck boi. ",
    "I'm in Göbeklitepe shirtless in a loincloth, blowin' bareback asshole out smokin' aqueduct filtered sherm. ",
    "Told shorty to keep that box breathin'. Yeah, she's squeezin' the garlic. ",
    "We smokin' Java, man. ",
    "Face pressed up against that monkey sniffin' for dear life. ",
    "The Cuban link will turn the diamond tester into a pipe bomb. ",
    "Glock 34 shivered his timbers. ",
    "Blew her back out usin' a mama-skin condom. ",
    "Dick pussy free-ballin' like Shaq and Kobe. ",
    "I'm smokin' Mesopotamian, Stanley Cup, triple award-winning, soul bleeder, taint blaster, JD Power Associates, dingleberry zaza. ",
    "We smokin' that IBM quantum computer. ",
    "I can't wait to curb stomp you in these dumb ugly-ass Rick Owen shoes. ",
    "I'm Dracula. I'm 12 million years old. ",
    "When I hit it from behind, the room smells like absolute Meechee. ",
    "They said I wouldn't shit on them. ",
    "I spread my cheeks and hit 'em with an absolute screamer. ",
    "Little bro was emaciated. ",
    "The percs done ate little cuzo ass up. ",
    "These cops are interrogating me about an ounce of weed as if I didn't kill an Applebee's hostess two miles away. ",
    "I come from a long bloodline of Italian leather. ",
    "My Bottegas have veins pumpin' through them. ",
    "Smokin' indigenous fronto leaf in a bacon, egg and cheese, hashtag Le Chemin du Roi. ",
    "Eyes bloodshot, leanin' up against the wall, beaten off to my Chrome Hearts boots. ",
    "Opps was talkin' crazy. Shot 'em in the mouth. ",
    "My Audemars Piguet worth the GDP of Yemen. ",
    "If this watch breaks, the foreign exchange market will take a 28% hit. People will die. ",
    "My diamonds come from the most horrific situations possible. ",
    "Slurpin' a quick release perc off the plate like a pinto bean. ",
    "I keep my Glock at the Vatican. ",
    "She squirt on me. I love being covered in the Chichi manga. ",
    "They're sick in the head. ",
    "They forgot I'm him. I'm him-ulation. I am Him Kardashian, Himbuktu, Himon and Pumbaa. ",
    "I got my DNA test back, turns out I'm a hundred percent Himalayan. Fuck it. ",
    "I ate the opp. ",
    "She let me hit it. ",
    "That gash sound like salmon roe. ",
    "You ran off with the Diddy Kong, triple espresso, personal hotspot, stem gripper runs. ",
    "There are consequences to your crimes against Dracula. ",
    "Get shorty outta here. She's built like a Jay Electronica verse. ",
    "I swear Bezos said it best. I'm a mud baby. I can't stop. ",
    "I have more percs than there are stars in the Leo cluster. ",
    "I'm claiming every corner, every block. Fuck it. I'm coming for every enzyme. ",
    "Snortin' dexy, eatin' skate right outta the lake. ",
    "Opp was sneak dissin' on the Gram turned his city into Pompeii. ",
    "These ain't no mall mange, you ugly bastard. ",
    "They want to drive a wooden stake into my heart for pullin' my cock out at the Toronto Blue Jays game. All I'm saying is I paid for the tickets. ",
    "My Ducati leather trench coat bright red. I look like 10 million crawdads fuckin'. ",
    "That elite pussy turned me into a radical. ",
    "I'm movin' lucrative. ",
    "I'm in the pod smokin' sa-boo-ba, smokin' that good shoo-be-doo-wa. ",
    "I'm fucked up in the crib listening to Trill Sammy. ",
    "I'm on the Ivory Coast eating vermilion snapper. ",
    "War is all I think about. I've never been scared in my life, jit. ",
    "This shit ain't nothin' to me, man.",
    "I need my percs. I need my percs. One perc is never enough. ",
    "Popped a Brazilian butt berserker and had that pussy screechin' like a harpy eagle. ",
    "I'm smokin' that shit that makes the toes curl. ",
    "I'm doin' a lotta drugs, a lot. ",
    "Walked along the sand dunes of the Sahara Desert for 40 days and 40 nights with nothin' but a of Newports and a fifth of Henny. I really do this shit.",
    "I'm startin' to get real pissed off. ",
    "What the fuck is Obamacare? Hey Obama, I don't care about shit. ",
    "Look at this shit. ",
    "I sold crack to myself, spun around the block so many times they thought it was fuckin' Minecraft. ",
    "We smokin' that Boomhauer. ",
    "Choked his goofy ass out with a B.B. Simon belt. ",
    "She wanted dick, but I gave her crack. ",
    "I'm smokin' lizard taint, sniffing monkey. It's Monkey Monday. Show me that monkey. ",
    "Ah! I'm gettin' too much money. ",
    "I'm fucked up drinkin' a Chinese Modelo. ",
    "I'm smokin' on that hush puppy limón. ",
    "Broke boy wasn't ballin' enough. ",
    "Welcome to the Wong Dong Tigers. ",
    "These Ferragamo's are real, cunt. ",
    "I got more sticks than a fucking forest. ",
    "I have the blueprint to the catacombs Pop four flimflams at KOD came out with hepatitis. ",
    "This shit ain't nothing to me, man. I'll fuckin' kill you. ",
    "I smoked a new opp. His meat came right off the bones. ",
    "The first time I smoked runts, I coughed so fuckin' hard. I started passin' kidney stones, then shat myself in front of the gang. There was scat all over the pounds we shipped out for the next 30 business days. ",
    "I don't have any compassion for broke boys. ",
    "Everybody has an asshole. Most people have dick and balls. ",
    "Go outside and get a bag. ",
    "I knew the perc was fake, but I still ate it because I'm a gremlin. ",
    "I'll air this bitch out like I shit in it. ",
    "I took two Limitless pills to limit myself. ",
    "I got so much cheese in my pocket, they thought I was a fuckin' calzone. ",
    "That pussy balder than Howie Mandell. ",
    "Crashed the Benz truck, sip some mud, everything felt alright. ",
    "Popped a bean, now I want to kill someone. ",
    "Yeah, I drill with my mask off. ",
    "I'm moving like Gilbert Arenas, snippin' white phosphorus. ",
    "The Vatican wants to wet me up with silver bullets, but I'm on a goddamn samurai pill. ",
    "I'm a real creature. ",
    "I'll spin the block, huffin' spores, to see tomorrow's stock market. ",
    "Lungs lookin' crazy. ",
    "Rollin' the ol' flesh cigar around your fingertips. ",
    "Boy ran off with a Banjo Kazooie. I had to cast a spell on that motherfucker. ",
    "I got strands of RNA in my hookah. Every puff is an insult to God. ",
    "The dust pack got me doing the third-world stare. ",
    "This zaza will give you a 2019 Alex Caruso hairline.",
    "Chopper small and sturdy, built like Wilmer Valderrama. ",
    "I let her hit the zaza just to buy her a bit more time, but all she wanted to do was fuck my brains out, then euthanize herself. ",
    "Dehydrated the soot between her ass cheeks and snorted that shit through my eyelids. ",
    "Trackhawks sound like game seven. Yahoo! ",
    "I'll give you that fluoride stare. ",
    "Pussy's so tight, I had to scissor her ass. This Henny got me feelin' crazy. ",
    "This Henny got me wantin' to shit. ",
    "This Henny got me feelin' like DDG. ",
    "My bitch pussy fatter than Druski. ",
    "Drank man, please! I'm thirsty. I'm ready. I'm trying to pour up. ",
    "Drank man, please! This Henny makin' me want to go to the mall and do somethin' crazy. ",
    "If Santa come down my chimney, I'mma fuck him. ",
    "That's what my Hellcat sounds like. ",
    "This shit ain't nothin' to me, man.",
    "I watch the cultivators spend hours rubbing the sticky out from the bedeviled shrub atop my pagoda. I pay them in Tibetan bullion coins.",
    "I smoke the shit that comes out of Northern Bharat.",
    "Took one puff of my alter ego's hash, commanded him to kiss my Berluti's if he didn't want me to make him eat his dirt.",
    "Do you see my Smith & Wesson? Fuck no, I already capped you.",
    "I'm so good with words, I gave a motherfucker a cordon bleu and made him tie it around his neck.",
    "God excommunicated me from the Silver City after I shat in his potted salvia, so I made Lucifer give me the keys to his domain. I sent his ass crying back to Daddy right after.",
    "This shit ain't nothing to me, man.",
    "I walked up into Sly's personal space and made it mine.",
    "I robbed Willem Dafoe of his Salade just to hide my balding cranium. Should've taken his hair, too.",
    "This shit'll make you see Bob Marley's naked spectre.",
    "Smoked a whole root of ayahuasca, now I'm dancing with the uncontacted peoples' lineage in the 4th dimension.",
    "I touched the untouchables just to fuck with'em.",
    "I tapped that ass so good, she thought I was The Great Khali.",
    "I haven't slumbered for so many eons, I can't tell if I'm hallucinating because of the sleep deprivation or if it's because of the Gorilla Glue Lemon.",
    "I had to isolate myself from the chums just so that they didn't have too much fun. Gotta keep'em needing for more.",
    "I graft my own skin off and suck on it like an Amazonian tree frog just to feel something.",
    "I had to do it to'em, Snipe.",
    "I exhaled right into Snoop's nostrils, had him crawling right back into his dilapidated, red kennel.",
    "I chill with the Apaches while they recite unwritten hymns and share a pipe packed with some shit I ain't ever witnessed.",
    "I pulled up and asked for the opp's coordinates, they said this was a Jamba Juice.",
    "The cedars be speaking to me in Akkadian. I planted those fuckers. I drink the sap from Pandora's tentacle trees. Not for the high, it's just a fetish.",
    "I made it to the edge of the omniverse, didn't like what I saw, so I made haste back to the manor and pacified myself with some Norwegian milkers.",
    "You can't make this shit up.",
    "I'm over here consuming genetically modified, crime syndicate portobello mushrooms while you're still there munching on organic Shiitake caps like a fucking peasant. Just try to get on my level, I dare you.",
    "Look into my eyes, you'll see the souls of those three carpet weavers I had to put down back in Morocco when they saw that I was using the fruits of their labor to roll some tenacious endo. I wasn't even gonna smoke that shit, it was a smuggling operation.",
    "That Californian female genitalia got me zooted.",
    "This 1cP-LSD is taking too long to peak, I need to sniff some gasoline.",
    "This shit's got me roaring like Aslan when he's schooling the white bitch.",
    "Somebody get me a benzo, the boogeyman's trying to fuck with me and he doesn't know that I'm strapped.",
    "I pluck the pubes off of my harem and smoke them with the gang up in the Hong Kong HSBC Tower while I wait for the transaction to go through.",
    "I'm over here consuming genetically modified, crime syndicate portobello mushrooms while you're still there munching on organic Shiitake caps like a fucking peasant. Just try to get on my level, I dare you.",
]
